model_params:
  name: 'VanillaVAE'
  in_channels: 1
  latent_dim: 128

exp_params:
  dataset: speckle
  data_path: "/Users/kenfujimoto/Downloads/speckle_Al2O3_2/"
  data_num: 1152
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 0.95

trainer_params:
  gpus: 0
  # max_nb_epochs: 50
  max_epochs: 100
  val_check_interval: 5

logging_params:
  save_dir: "logs/"
  name: "VanillaVAE"
  manual_seed: 1265
