model_params:
  name: 'VQVAE'
  in_channels: 1
  embedding_dim: 64
  num_embeddings: 512
  img_size: 64
  beta: 0.25

exp_params:
  dataset: speckle
  data_path: "/Users/kenfujimoto/Downloads/speckle_Al2O3_2/"
  data_num: 1152
  img_size: 64
  batch_size: 144 # Better to have a square number
  LR: 0.001
  weight_decay: 0.0
  scheduler_gamma: 0.0

trainer_params:
  gpus: 0
  # max_nb_epochs: 50
  max_epochs: 30

logging_params:
  save_dir: "logs/"
  name: "VQVAE"
  manual_seed: 1265
